---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-cluster-ica
  namespace: istio-system
spec:
  secretName: cacerts
  commonName: {{.Values.clusterName}}
  isCA: true
  duration: 43800h
  renewBefore: 8760h
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: vault-ica
    kind: Issuer
