# Single arch:
# git checkout 1.16.0
# docker build -t h0tbird/pilot:1.16.0 -f Dockerfile.pilot-discovery .

# Multi arch:
# git checkout 1.16.0
# docker buildx build --platform linux/amd64,linux/arm64 -t h0tbird/pilot:1.16.0 -f Dockerfile.pilot-discovery --push .

# Debug:
# k --context kube-01 -n httpbin exec -it deployments/sleep -c istio-proxy -- sudo bash -c 'echo 0 > /proc/sys/kernel/yama/ptrace_scope'
# k --context kube-01 -n httpbin exec -it deployments/sleep -c istio-proxy -- dlv dap --listen=:40000 --log=true
# k --context kube-01 -n httpbin port-forward deployments/sleep 40000:40000

#------------------------------------------------------------------------------
#
#------------------------------------------------------------------------------

FROM golang:1.19 AS builder

WORKDIR /workspace

# Cache dependencies
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

# Copy the code
COPY pilot/ pilot/
COPY pkg/ pkg/
COPY operator/ operator/
COPY security/ security/
COPY tools/ tools/
COPY common/ common/
COPY manifests/ manifests/

# Build
RUN CGO_ENABLED=0 go build -o pilot-discovery -gcflags=all="-N -l" -ldflags '\
-extldflags "-static -s -w" \
-X istio.io/pkg/version.buildVersion=1.16.0 \
-X istio.io/pkg/version.buildGitRevision=8f2e2dc5d57f6f1f7a453e03ec96ca72b2205783 \
-X istio.io/pkg/version.buildStatus=debug \
-X istio.io/pkg/version.buildTag=1.16.0 \
-X istio.io/pkg/version.buildHub=docker.io/h0tbird' \
./pilot/cmd/pilot-discovery

# Install delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

#------------------------------------------------------------------------------
#
#------------------------------------------------------------------------------

FROM istio/pilot:1.16.0

USER 0:0

# Install tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    file && rm -rf /var/lib/apt/lists/*

# Copy binaries and source code
COPY --from=builder /go/bin/dlv /usr/local/bin/dlv
COPY --from=builder /workspace /workspace
COPY --from=builder /go /go
RUN mv /workspace/pilot-discovery /usr/local/bin/

USER 1337:1337
