apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    cni:
      enabled: true
  values:
    cni:
      logLevel: info
      privileged: true
      ambient:
        enabled: true
      cniBinDir: /var/lib/rancher/k3s/data/current/bin
      cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
      pullPolicy: IfNotPresent
      excludeNamespaces:
      - istio-system
      - kube-system
