apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/istio
  components:
    base:
      enabled: true
  values:
    global:
      proxy:
        privileged: true
        enableCoreDump: true
        clusterDomain: domain-XXXX
      meshID: mesh-XXXX
      multiCluster:
        clusterName: cluster-XXXX
      network: network-XXXX
