apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: ghcr.io/resf/istio
  components:
    base:
      enabled: true
  values:
    global:
      proxy:
        privileged: true
      meshID: mesh-XXXX
      multiCluster:
        clusterName: cluster-XXXX
      network: network-XXXX
