apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: ghcr.io/resf/istio
  components:
    pilot:
      enabled: true
      k8s:
        replicaCount: 1
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
          patches:
          - path: spec.template.spec.containers[0].lifecycle
            value:
              preStop:
                exec:
                  command: ["sleep", "5"]
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
  values:
    istio_cni:
      enabled: true
    pilot:
      autoscaleEnabled: false
      env:
        PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
        PILOT_ENABLE_WORKLOAD_ENTRY_HEALTHCHECKS: true
        ISTIOD_CUSTOM_HOST: istiod.cluster-XXXX
        ENABLE_CA_SERVER: false
    global:
      meshID: mesh-XXXX
      multiCluster:
        clusterName: cluster-XXXX
      network: network-XXXX
      logAsJson: true
