apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: ghcr.io/resf/istio
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        replicaCount: 1
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istio-ingressgateway
          patches:
          - path: spec.template.spec.containers[0].lifecycle
            value:
              preStop:
                exec:
                  command: ["sleep", "5"]
  values:
    global:
      meshID: mesh-XXXX
      multiCluster:
        clusterName: cluster-XXXX
      network: network-XXXX
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        injectionTemplate: gateway
