apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    pilot:
      enabled: true
      k8s:
        replicaCount: 1
        # overlays:
        # - apiVersion: apps/v1
        #   kind: Deployment
        #   name: istiod-revision-XXXX
        #   patches:
        #   - path: spec.template.spec.containers[0].image
        #     value: docker.io/h0tbird/pilot:1.16.0
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    trustDomain: trustDomain-XXXX
  values:
    istio_cni:
      enabled: true
    pilot:
      autoscaleEnabled: false
      env:
        AUTO_RELOAD_PLUGIN_CERTS: true
        PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
        PILOT_ENABLE_WORKLOAD_ENTRY_HEALTHCHECKS: true
        ISTIOD_CUSTOM_HOST: istiod.cluster-XXXX
