apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    pilot:
      enabled: true
      k8s:
        replicaCount: 1
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_ENABLE_HBONE: "true"
    trustDomain: trustDomain-XXXX
  values:
    istio_cni:
      enabled: true
    pilot:
      autoscaleEnabled: false
      env:
        VERIFY_CERTIFICATE_AT_CLIENT: true
        ENABLE_AUTO_SNI: true
        AUTO_RELOAD_PLUGIN_CERTS: true
        PILOT_ENABLE_HBONE: true
        PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
        PILOT_ENABLE_WORKLOAD_ENTRY_HEALTHCHECKS: true
        PILOT_ENABLE_AMBIENT_CONTROLLERS: true
        CA_TRUSTED_NODE_ACCOUNTS: "istio-system/ztunnel,kube-system/ztunnel"
        ISTIOD_CUSTOM_HOST: istiod.cluster-XXXX
