apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    ztunnel:
      enabled: true
      k8s:
        env:
          - name: XDS_ADDRESS
            value: https://istiod-revision-XXXX.istio-system.svc:15012
          - name: CA_ADDRESS
            value: https://istiod-revision-XXXX.istio-system.svc:15012