apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: istio-system
    topology.istio.io/network: {{ .Values.network }}
  name: istio-system
spec:
  finalizers:
  - kubernetes
